apiVersion: v1
kind: Namespace
metadata:
  name: odilomail
---
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: odilomail
  namespace: odilomail
spec:
  schema:
    apiVersion: v1alpha1
    kind: Odilomail
    spec:
      deployment:
        replicas: integer
        image: string
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          replicas: ${schema.spec.deployment.replicas}
          selector:
            matchLabels:
              app: ${schema.metadata.name}
          template:
            metadata:
              labels:
                app: ${schema.metadata.name}
            spec:
              containers:
                - name: ${schema.metadata.name}
                  image: ${schema.spec.deployment.image}
                  ports:
                    - containerPort: 80
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          type: ClusterIP
          selector:
            app: ${schema.metadata.name}
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
    - id: loadbalancerconfiguration
      template:
        apiVersion: gateway.k8s.aws/v1beta1
        kind: LoadBalancerConfiguration
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          scheme: internet-facing
          loadBalancerSubnets:
            - identifier: subnet-0390d8f395fd0f9bf
            - identifier: subnet-0bf7ac29bffc2d0b2
    - id: gateway
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          gatewayClassName: gateway
          infrastructure:
            parametersRef:
              group: gateway.k8s.aws
              kind: LoadBalancerConfiguration
              name: ${schema.metadata.name}
          listeners:
          - name: http
            protocol: HTTP
            port: 80
            allowedRoutes:
              namespaces:
                from: Same
    - id: targetgroup
      template:
        apiVersion: gateway.k8s.aws/v1beta1
        kind: TargetGroupConfiguration
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          routeConfigurations:
            - routeIdentifier:
                kind: HTTPRoute
                name: ${schema.metadata.name}
                namespace: ${schema.metadata.namespace}
          targetReference:
            name: ${schema.metadata.name}
          defaultConfiguration:
            targetType: ip
    - id: httproute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: ${schema.metadata.name}
            sectionName: http
          hostnames:
            - odilomail.com
          rules:
            - backendRefs:
              - name: ${schema.metadata.name}
                port: 80
              matches:
                - path:
                    type: PathPrefix
                    value: /odilomail