apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
- |-
  apiVersion: gateway.k8s.aws/v1beta1
  kind: LoadBalancerConfiguration
  metadata:
    name: alb
    namespace: default
  spec:
    loadBalancerSubnets:
      - identifier: subnet-0390d8f395fd0f9bf
      - identifier: subnet-0bf7ac29bffc2d0b2