apiVersion: v1
kind: Namespace
metadata:
  name: mondareader
  labels:
    shared-gateway-access: "true"
---
apiVersion: kro.run/v1alpha1
kind: Nginx
metadata:
  name: mondareader
  namespace: mondareader
spec:
  deployment:
    replicas: 1
    image: nginx:latest
  configuration:
    hostname:
      - mondareader.com
    subnets:
      - identifier: subnet-0390d8f395fd0f9bf
      - identifier: subnet-0bf7ac29bffc2d0b2