releases:
- name: aws-load-balancer-controller
  namespace: kube-system
  chart: eks/aws-load-balancer-controller
  version: 1.16.0
  values:
    - charts/alb/values-{{ .Environment.Name }}.yaml
  verify: false
  needs:
  - default/gateway-api