clusterName: eks 
serviceAccount:
  create: false
  name: aws-load-balancer-controller
region: eu-west-1
vpcId: vpc-050c5148827881443
controllerConfig:
  featureGates:
    NLBGatewayAPI: true
    ALBGatewayAPI: true