environments:
  dev:
  pro:

bases:
  - charts/alb/releases.yaml
  - charts/alb/repositories.yaml
  - charts/gateway-api/releases.yaml
  - charts/gateway-api/repositories.yaml
  - charts/kro/releases.yaml
  - charts/kro/repositories.yaml